---

version: "2"

services:

  # AUTORITÉ DE CERTIFICATION
  ca:
    image: "debian:latest"
    volumes:
      # certificats
      - "./certs/ca_key_assr.pem:/etc/ssl/assr/ca_key_assr.pem"
      - "./certs/ca_cert_assr.pem:/etc/ssl/assr/ca_cert_assr.pem"
#      - "./certs/ca.cert.pem:/etc/ssl/ca/ca.cert.pem"
#      - "./certs/ca.privkey.pem:/etc/ssl/ca/ca.privkey.pem"
#      - "./certs/web.csr.pem:/etc/ssl/ca/web.csr.pem"
#      - "./certs/web.cert.pem:/etc/ssl/ca/web.cert.pem"
    command: "sleep infinity"

  # SERVER WEB
  nginx:
    image: "nginx:latest"
    volumes:
      # nginx
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      # certificats du serveur
      - "./certs/ca_key_assr.pem:/etc/ssl/assr/ca_key_assr.pem"
      - "./certs/ca_cert_assr.pem:/etc/ssl/assr/ca_cert_assr.pem"
#      - "./certs/web.cert.pem:/etc/ssl/assr/web.cert.pem"
#      - "./certs/web.csr.pem:/etc/ssl/assr/web.csr.pem"
#      - "./certs/web.csr.conf:/etc/ssl/assr/web.csr.conf"
      # html
      - "./www:/var/www"
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - "assr.google.com"

  # CLIENT WEB
  client:
    image: "drwetter/testssl.sh:latest"
    volumes:
      # certificat de la CA
      - "./certs/ca_key_assr.pem:/etc/ssl/assr/ca_key_assr.pem"
      - "./certs/ca_cert_assr.pem:/etc/ssl/assr/ca_cert_assr.pem"
#      - "./certs/ca.cert.pem:/usr/local/share/ca-certificates/cacert.crt"
#      - "./certs/:/tmp/testssl/"
    entrypoint: ""
    command: "sleep infinity"

...
